# Generated by Django 5.2 on 2025-05-15 05:27

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('file', models.FileField(blank=True, null=True, upload_to='contact_requests/%Y/%m/%d/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('awaiting_documents', 'Ожидает документы'), ('review', 'На проверке'), ('completed', 'Завершена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Контактная заявка',
                'verbose_name_plural': 'Контактные заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FNSNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('summary', models.TextField(verbose_name='Краткое содержание')),
                ('link', models.URLField(verbose_name='Ссылка на новость')),
                ('published', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость ФНС',
                'verbose_name_plural': 'Новости ФНС',
                'ordering': ['-published'],
            },
        ),
    ]
