# Generated by Django 5.2 on 2025-05-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='pd_agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПД'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='pd_agreement_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия'),
        ),
    ]
