# Generated by Django 5.1.5 on 2025-01-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='status',
        ),
    ]
