# Generated by Django 5.2 on 2025-05-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactrequest_pd_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contact_requests/'),
        ),
    ]
