# Generated by Django 5.2 on 2025-05-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_contactrequest_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contact_requests/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
