# Generated by Django 5.1.5 on 2025-01-31 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_contactrequest_request_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='request_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
