# Generated by Django 5.1.5 on 2025-01-31 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactrequest_request_number_contactrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='request_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True),
        ),
    ]
