# Generated by Django 5.2 on 2025-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_contactrequest_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FNSNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('summary', models.TextField(verbose_name='Краткое содержание')),
                ('link', models.URLField(verbose_name='Ссылка на новость')),
                ('published', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость ФНС',
                'verbose_name_plural': 'Новости ФНС',
                'ordering': ['-published'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Контактная заявка', 'verbose_name_plural': 'Контактные заявки'},
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='request_number',
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contact_requests/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
